### ISSUE TITLE
CSCwi58728 - Syntax Issues in AIRESPACE-WIRELESS-MIB.my

### ISSUE THREAD

**Issue by SuperQ** [cisco/cisco-mibs#19]
I'm still trying to figure out what went wrong, but #12 broke net-snmp parsing of this MIB.

**Comment by SuperQ** [comment]
@kyzer-davis, did the internal team ever fix the syntax issues?

**Comment by kyzer-davis** [comment]
Took a while but PR should be coming after I filed the internal defect:
CSCwi58728 - Syntax Issues in AIRESPACE-WIRELESS-MIB.my
