### ISSUE TITLE
CSCwi58734 - Syntax Issues in CISCO-LWAPP-AP-MIB.my

### ISSUE THREAD

**Issue by blk878s** [cisco/cisco-mibs#21]
**LINE: Description of error   ------Possible Fix**

1975: type of cLApFloorLabel in sequence and object type definition do not match 	  **------ Unsure of the fix for this**
5440: illegal keyword FALSE 	 **----  'FALSE' should be lowercase**  	  
10410: syntax error, unexpected '}', expecting UPPERCASE_IDENTIFIER or LOWERCASE_IDENTIFIER or NUMBER 	  **-----There is an unneeded comma (',') at the end of line 10409**	  
10534: default value syntax does not match object syntax    **---- Removing the default value seemed to fix this but I am not sure if that is correct**	  
4271: unknown object identifier label `cLApSlotWlanStatsTable' 	  **---- The object on line 4247 has the wrong name: it has cLApWlanSlotStatsTable and should be cLApSlotWlanStatsTable**  

**These last few errors have unknown object ids**

9937: type CLDot11Band of node cLApRogueDot11RadioBand does not resolve to a known base type
10410: unknown object identifier label `bsnStationAPIfSlotId'  10463: type CLApNtpStatus of node cLApNtpInfoStatus does not resolve to a known base type 	  	  
9939: unknown type CLDot11Band	  
10444: unknown type CLApNtpStatus

**Comment by kyzer-davis** [comment]
I let @vijaygu2 know to take a look since he published #12

**Comment by kyzer-davis** [comment]
Filed, CSCwi58734 - Syntax Issues in CISCO-LWAPP-AP-MIB.my
