### ISSUE TITLE
Recommended MIB files of MDS 9000 series for SNMP trap based monitoring

### ISSUE THREAD

**Issue by ashokbeh** [cisco/cisco-mibs#34]
Hi,
On going through  https://www.cisco.com/en/US/docs/storage/san_switches/mds9000/sw/san-os/mibs/reference/guide/MIBRef.html#wp85482 I learned there are lot many MIBs along with dependent MIBs.
We want to set up trap based monitoring solution for Cisco MDS 9000 series. Would appreciate if you can help us with recommended MIB file names to for our monitoring solution.

**Comment by kyzer-davis** [comment]
@ashokbeh, This probably is not the correct forum for questions of that nature. 
You may get a better response from either:
- Cisco Community Support Forums: https://community.cisco.com/
- Cisco Technical Assistance Center: https://www.cisco.com/c/en/us/support/web/tsd-cisco-worldwide-contacts.html

**Comment by ashokbeh** [comment]
Thank you Kyzer-Davis for your advice. Will check on other forums recommended by you.
