### ISSUE TITLE
CSCwi91154 - C9200CX missing from CISCO-PRODUCTS-MIB file

### ISSUE THREAD

**Issue by noziwatele** [cisco/cisco-mibs#59]
We have a C9200CX-12P-2X2G switch running IOS-XE 17.9.4 and our NMS and network discovery tools can't identify the model number from CISCO-PRODUCTS-MIB.

An SNMP get for `sysObjectID` finds that the switch identifies itself as product 3079. However there is no entry for 3079 in CISCO-PRODUCTS-MIB, as far as I can see.

This is the response from `sysObjectID`:

`SNMPv2-MIB::sysObjectID.0 = OID: SNMPv2-SMI::enterprises.9.1.3079`

I would suggest that an entry for this model is needed on [line 2745
](https://github.com/cisco/cisco-mibs/blob/9a24ff94ed7d75451114428e3f0ffddb790f1fea/v2/CISCO-PRODUCTS-MIB.my#L2745)

I don't know the official description, but the required line would probably be something like: 

`ciscoC9200CX12P2X2G                    OBJECT IDENTIFIER ::= { ciscoProducts 3079 } --  Catalyst 9200CX 12 ports PoE+, 2x 1G copper, 2x 10G SFP+ fixed uplinks. 315W AC internal power supply. Fanless.
`
(Product description from the [Cisco Catalyst 9200 Series Switches Data Sheet](https://www.cisco.com/c/en/us/products/collateral/switches/catalyst-9200-series-switches/nb-06-cat9200-ser-data-sheet-cte-en.html))

Could this be updated please?

**Edit:** I note that there are no C9200CX models at all in this MIB file so there are probably a number of other entries missing, but I can only confirm the model above.

**Comment by kyzer-davis** [comment]
Sure, I relayed this info to @vijaygu2 and team who handle updates to that file.

**Comment by kyzer-davis** [comment]
Fixed in #70
