### ISSUE TITLE
CSCwk68949 - Typo in Neighbor Discovery mode CISCO-LWAPP-DOT11-MIB

### ISSUE THREAD

**Issue by nielsb** [cisco/cisco-mibs#77]
cldDot11aNdpMode ::= { cldDot11dpMode 2 } at line 1663 in ../cisco-lwapp/CISCO-LWAPP-DOT11-MIB.my

I guess it should be  `{ cldDot11NdpMode 2 }` ?

**Comment by myhomenwlab** [comment]
I too think it is cldDot11"N"dpMode, not cldDot11dpMode.
Ndp = NDP (Neighbor Discovery Packet)

https://github.com/cisco/cisco-mibs/blob/main/v2/CISCO-LWAPP-DOT11-MIB.my#L1670
>     ::= { cldDot11dpMode 2 }

**Comment by kyzer-davis** [comment]
Yes, `{ cldDot11NdpMode 2 }` would jive with the whole section.

https://github.com/cisco/cisco-mibs/blob/main/v2/CISCO-LWAPP-DOT11-MIB.my#L1645C1-L1670C29

I will raise a defect.

**Comment by myhomenwlab** [comment]
A Pull Request #104 including the corrected code. It has not been merged yet.

https://github.com/cisco/cisco-mibs/pull/104/files#diff-fc9e7979157ab4565e624cb328c9b29b618a0569b95b60afddb8601c77767b70R1669
